/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompatibilityCheckResponse : Compatibility check response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompatibilityCheckResponse {
    /// Whether the compared schemas are compatible
    #[serde(rename = "is_compatible", skip_serializing_if = "Option::is_none")]
    pub is_compatible: Option<bool>,
    /// Error messages
    #[serde(rename = "messages", skip_serializing_if = "Option::is_none")]
    pub messages: Option<Vec<String>>,
}

impl CompatibilityCheckResponse {
    /// Compatibility check response
    pub fn new() -> CompatibilityCheckResponse {
        CompatibilityCheckResponse {
            is_compatible: None,
            messages: None,
        }
    }
}

