/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubjectVersion : Subject version pair
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectVersion {
    /// Name of the subject
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Version number
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl SubjectVersion {
    /// Subject version pair
    pub fn new() -> SubjectVersion {
        SubjectVersion {
            subject: None,
            version: None,
        }
    }
}

